FROM ubuntu:16.04

LABEL maintainer="jkarjala@broadinstitute.org"

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update && \
    apt-get install curl make gcc g++ cmake gfortran libreadline-dev \
    libz-dev libzstd-dev libbz2-dev liblzma-dev libpcre3-dev libssl-dev libcurl4-openssl-dev \
    libopenblas-dev default-jre unzip libboost-all-dev \
    libpng-dev libcairo2-dev tabix --yes && \
    apt-get clean && \
    curl -O https://cloud.r-project.org/src/base/R-3/R-3.5.1.tar.gz && \
    tar xvzf R-3.5.1.tar.gz && \
    cd R-3.5.1 && \
    ./configure --with-x=no --enable-R-shlib=yes --with-blas="-lopenblas" && \
    make && \
    mkdir -p /usr/local/lib/R/lib && \
    make install && \
    cd .. && \
    rm -rf R-3.5.1*

ADD SAIGE/thirdParty /SAIGE/thirdParty

RUN apt-get install python3-pip --yes && \
    pip3 install cget pysam && \
    apt-get remove default-jre --yes && apt autoremove --yes && apt-get clean

RUN apt install libxml2-dev

ADD SAIGE/extdata/install_packages.R /usr/local/bin/
RUN chmod a+x /usr/local/bin/install_packages.R && install_packages.R

ADD SAIGE /SAIGE

RUN R CMD INSTALL SAIGE && \
    rm -rf SAIGE

ADD SAIGE/extdata/step1_fitNULLGLMM.R SAIGE/extdata/step2_SPAtests.R scripts/qqplot.R /usr/local/bin/
RUN chmod a+x /usr/local/bin/step1_fitNULLGLMM.R /usr/local/bin/step2_SPAtests.R /usr/local/bin/qqplot.R
